# Generated by Django 5.2 on 2025-06-19 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "propietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proyectos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyecto",
                "verbose_name_plural": "Proyectos",
                "ordering": ["-creado"],
            },
        ),
        migrations.CreateModel(
            name="Fase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fases",
                        to="documentacion.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fase",
                "verbose_name_plural": "Fases",
                "ordering": ["nombre"],
                "unique_together": {("proyecto", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="SubArtefacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("enlace", models.URLField(blank=True)),
                (
                    "fase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subartefactos",
                        to="documentacion.fase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subartefacto",
                "verbose_name_plural": "Subartefactos",
                "ordering": ["nombre"],
                "unique_together": {("fase", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="Artefacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("AREQ", "Análisis de Requisitos"),
                            ("DISE", "Diseño"),
                            ("DEVS", "Desarrollo"),
                            ("PRUE", "Pruebas"),
                            ("DESP", "Despliegue"),
                        ],
                        max_length=4,
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("contenido", models.TextField()),
                ("generado_por_ia", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "fase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artefactos",
                        to="documentacion.fase",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artefactos",
                        to="documentacion.project",
                    ),
                ),
                (
                    "subartefacto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artefactos",
                        to="documentacion.subartefacto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Artefacto",
                "verbose_name_plural": "Artefactos",
                "ordering": ["-creado"],
            },
        ),
    ]
