# Generated by Django 5.2 on 2025-10-03 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentacion", "0002_artefacto_contexto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pregunta1", models.CharField(max_length=200)),
                ("respuesta1", models.CharField(max_length=200)),
                ("pregunta2", models.CharField(max_length=200)),
                ("respuesta2", models.CharField(max_length=200)),
                ("pregunta3", models.CharField(max_length=200)),
                ("respuesta3", models.CharField(max_length=200)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregunta de Seguridad",
                "verbose_name_plural": "Preguntas de Seguridad",
            },
        ),
    ]
