# Generated by Django 5.2 on 2025-10-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentacion", "0003_securityquestions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityquestions",
            name="pregunta1",
            field=models.CharField(
                choices=[
                    ("color", "¿Cuál es tu color favorito?"),
                    ("comida", "¿Cuál es tu comida favorita?"),
                    ("pelicula", "¿Cuál es tu película favorita?"),
                    ("libro", "¿Cuál es tu libro favorito?"),
                    ("deporte", "¿Cuál es tu deporte favorito?"),
                    ("musica", "¿Cuál es tu género de música favorito?"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="securityquestions",
            name="pregunta2",
            field=models.CharField(
                choices=[
                    ("color", "¿Cuál es tu color favorito?"),
                    ("comida", "¿Cuál es tu comida favorita?"),
                    ("pelicula", "¿Cuál es tu película favorita?"),
                    ("libro", "¿Cuál es tu libro favorito?"),
                    ("deporte", "¿Cuál es tu deporte favorito?"),
                    ("musica", "¿Cuál es tu género de música favorito?"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="securityquestions",
            name="pregunta3",
            field=models.CharField(
                choices=[
                    ("color", "¿Cuál es tu color favorito?"),
                    ("comida", "¿Cuál es tu comida favorita?"),
                    ("pelicula", "¿Cuál es tu película favorita?"),
                    ("libro", "¿Cuál es tu libro favorito?"),
                    ("deporte", "¿Cuál es tu deporte favorito?"),
                    ("musica", "¿Cuál es tu género de música favorito?"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="securityquestions",
            name="respuesta1",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="securityquestions",
            name="respuesta2",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="securityquestions",
            name="respuesta3",
            field=models.CharField(max_length=100),
        ),
    ]
